method_name: ddpm
experiment_name: mmnist-medium

device: cuda
dataset_dir: data/mmnist-medium
train_batch_size: 4
num_frames: 1

num_epochs: 1
train_steps: 2048
learning_rate: 1.0e-3

output_dir: ddpm-test

seed: 0

ema:
  decay: 0.995

noise_scheduler:
  num_diffusion_steps: 100
  beta_start: 1.0e-4
  beta_end: 0.02

infer:
  trained_weights: weights/ddpm-mmnist-medium
  num_frames_to_infer: 100
  num_videos_to_generate: 2

wandb:
  use_wandb: true
  group: train
  tags: [ test, debug ]
  save_weights_to_wandb: true
  steps_to_log_images: 100

