method_name: ddpm
experiment_name: mmnist-hard

device: cuda
dataset_dir: data/mmnist-hard
train_batch_size: 64
num_frames: 40

num_epochs: 1
train_steps: 5050 
learning_rate: 5.0e-4

output_dir: ddpm-test

seed: 0

ema:
  decay: 0.995

noise_scheduler:
  num_diffusion_steps: 1000  # 1000
  beta_start: 1.0e-4
  beta_end: 0.02

infer:
  trained_weights: weights/ddpm-mmnist-hard
  num_frames_to_infer: 60
  num_videos_to_generate: 1

hierarchical_infer:
  total_num_frames_to_infer: 20
  num_frames_to_generate_after_each_key_frame: 3
  output_fps: 5

keyframe_model:
  trained_weights: weights/ddpm-mmnist-medium-keyframe
  num_frames_to_skip_per_keyframe: 3
  limit_batch_size: 2

wandb:
  use_wandb: true
  group: train
  tags: [ test, debug ]
  save_weights_to_wandb: true
  steps_to_log_images: 100
  num_images_to_infer_during_training: 1 # Set to 5 for normal model; 1 for keyframe model

